"""Interactive init wizard for creating new agent projects."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

if TYPE_CHECKING:
    pass


def run_init_wizard(output_dir: Path, name: str | None, console: Console) -> None:
    """
    Run the interactive init wizard.

    Args:
        output_dir: Directory to create files in.
        name: Optional pre-provided name.
        console: Rich console for output.
    """
    console.print(Panel.fit(
        "[bold blue]EZ-Agent Project Initialization[/bold blue]\n"
        "Answer the following questions to create your agent configuration.",
        border_style="blue",
    ))

    # Gather information
    agent_name = name or Prompt.ask(
        "\n[cyan]Agent name[/cyan]",
        default="MyAgent",
    )

    description = Prompt.ask(
        "[cyan]Description[/cyan]",
        default=f"{agent_name} - An AI assistant",
    )

    model = Prompt.ask(
        "[cyan]Model[/cyan]",
        default="gpt-4o",
    )

    # Provider selection
    console.print("\n[bold]Select LLM Provider:[/bold]")
    console.print("  1. Azure AI Foundry (recommended)")
    console.print("  2. Local (for development)")

    provider_choice = Prompt.ask(
        "[cyan]Provider[/cyan]",
        choices=["1", "2"],
        default="1",
    )

    provider = "azure_foundry" if provider_choice == "1" else "local"

    # Azure-specific configuration
    azure_endpoint = None
    if provider == "azure_foundry":
        azure_endpoint = Prompt.ask(
            "[cyan]Azure AI Foundry endpoint[/cyan]",
            default="${AZURE_AI_ENDPOINT}",
        )

    # Features
    console.print("\n[bold]Enable features:[/bold]")
    enable_streaming = Confirm.ask("  Enable streaming responses?", default=True)
    enable_tools = Confirm.ask("  Enable tool execution?", default=True)
    enable_history = Confirm.ask("  Enable conversation history?", default=True)

    # Instructions
    console.print("\n[cyan]Enter system instructions (press Enter for default):[/cyan]")
    instructions = Prompt.ask(
        "Instructions",
        default=f"You are {agent_name}, a helpful AI assistant. Be concise, accurate, and friendly.",
    )

    # Generate configuration
    config_content = _generate_config(
        name=agent_name,
        description=description,
        model=model,
        provider=provider,
        azure_endpoint=azure_endpoint,
        instructions=instructions,
        streaming=enable_streaming,
        tools=enable_tools,
        history=enable_history,
    )

    # Write files
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / f"{agent_name.lower().replace(' ', '-')}.yaml"
    config_path.write_text(config_content)

    console.print(f"\n[green]✓ Created configuration: {config_path}[/green]")

    # Create example tools file if tools enabled
    if enable_tools:
        tools_path = output_dir / "tools.py"
        tools_content = _generate_example_tools()
        tools_path.write_text(tools_content)
        console.print(f"[green]✓ Created example tools: {tools_path}[/green]")

    # Show next steps
    console.print(Panel.fit(
        "[bold]Next Steps:[/bold]\n\n"
        f"1. Review your configuration in [cyan]{config_path}[/cyan]\n"
        "2. Set environment variables (e.g., AZURE_AI_ENDPOINT)\n"
        f"3. Run your agent: [cyan]ezagent run -c {config_path} -m terminal[/cyan]",
        title="Setup Complete",
        border_style="green",
    ))


def _generate_config(
    name: str,
    description: str,
    model: str,
    provider: str,
    azure_endpoint: str | None,
    instructions: str,
    streaming: bool,
    tools: bool,
    history: bool,
) -> str:
    """Generate YAML configuration content."""
    config = f'''# EZ-Agent Configuration
# Generated by: ezagent init

name: {name}
description: {description}
version: 1.0.0

instructions: |
  {instructions}

model: {model}

configuration:
  provider: {provider}
'''

    if provider == "azure_foundry" and azure_endpoint:
        config += f'''  azure:
    endpoint: {azure_endpoint}
    auth_method: default_credential
'''

    config += f'''
  logging:
    level: INFO
    format: console

  auth:
    enabled: false

features:
  streaming: {str(streaming).lower()}
  tool_execution: {str(tools).lower()}
  conversation_history: {str(history).lower()}

tools: []
  # Example function tool:
  # - name: get_weather
  #   type: function
  #   module: tools
  #   function: get_weather
  #
  # Example HTTP tool:
  # - name: search_api
  #   type: http
  #   endpoint: https://api.example.com/search
  #   method: POST
'''

    return config


def _generate_example_tools() -> str:
    """Generate example tools Python file."""
    return '''"""Example tools for your EZ-Agent.

Register these in your agent configuration:

tools:
  - name: get_weather
    type: function
    module: tools
    function: get_weather
"""

from ez_agent.tools import tool


@tool()
def get_weather(city: str, units: str = "celsius") -> str:
    """
    Get the current weather for a city.

    Args:
        city: The city name to get weather for.
        units: Temperature units (celsius or fahrenheit).

    Returns:
        Weather information as a string.
    """
    # This is a placeholder - integrate with a real weather API
    return f"Weather in {city}: Sunny, 22°{'C' if units == 'celsius' else 'F'}"


@tool()
def calculate(expression: str) -> str:
    """
    Evaluate a mathematical expression.

    Args:
        expression: A mathematical expression to evaluate (e.g., "2 + 2 * 3").

    Returns:
        The result of the calculation.
    """
    # Simple and safe evaluation for basic math
    allowed_chars = set("0123456789+-*/.() ")
    if not all(c in allowed_chars for c in expression):
        return "Error: Invalid characters in expression"

    try:
        result = eval(expression, {"__builtins__": {}}, {})
        return str(result)
    except Exception as e:
        return f"Error: {e}"


@tool(name="current_time", description="Get the current date and time")
async def get_current_time() -> str:
    """Get the current date and time in ISO format."""
    from datetime import datetime
    return datetime.now().isoformat()
'''
